name: Publish Release

on:
  workflow_dispatch:
    inputs:
      tag:
        description: 'The pyzef-x tag of the release'
        required: true
        type: string

jobs:
  upload-zefops:
    name: Deploy zefops docstrings to zef-docs.
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
        with:
          path: /home/runner/work/zef/zef
          token: ${{ secrets.GITHUB_TOKEN }}
          tag: pyzef-${{ github.event.inputs.tag }}

      - name: Setup python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8

      - name: Grab built wheel
        env:
          ZEF_VERSION: ${{ github.event.inputs.tag }}
        run: |
          python3 -mpip install zef==${ZEF_VERSION}

      ########
      # Generate docs
      - name: Run extract docstrings script
        run: |
          # export PYTHONPATH="${GITHUB_WORKSPACE}/zef:$PYTHONPATH"
          # echo $PYTHONPATH
          python zef/scripts/extract-docstrings.py
      - uses: actions/checkout@v2
        with:
          repository: zefhub/zef-docs
          path: /home/runner/work/zef/zef-docs
          token: ${{ secrets.GIT_ACCESS_KEY }}
          persist-credentials: true
      - run: |
          mv zef-ops.mdx /home/runner/work/zef/zef-docs/docs/zef-ops.mdx
          cd /home/runner/work/zef/zef-docs
          git status
          git config user.email "thedanielforum@gmail.com"
          git config user.name "Zef Bot by Github Actions"
          git add docs/zef-ops.mdx
          git commit -m "Auto generated zef-ops docs from docstrings in Zef repo."
          git push origin master

  publish-announcement:
    name: Publish announcement of new release
    runs-on: ubuntu-20.04
    needs: [upload-zefops]
    steps:
      - uses: actions/checkout@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          persist-credentials: true

      - name: Get announcement details
        id: release-details
        run: |
          curl -H "Accept: application/vnd.github.v3+json" https://api.github.com/repos/zefhub/zef/releases/tags/$ZEF_TAG -o curl.out || exit 1
          cat curl.out | jq -r .body > release.body || exit 1
          title=$(cat curl.out | jq -r .name)
          echo ::set-output name=title::${title}

      - name: Release announcement
        env:
          MATTERMOST_URL: ${{ secrets.MATTERMOST_URL }}
          CHANNEL: "releases"
          NAME: ${{ steps.release-details.outputs.title }}
          DESCRIPTION_FILE: "release.body"
          VERSION_STRING: ${{ github.events.inputs.tag }}
          DOWNLOAD_STRING: "`pip3 install --upgrade zef`"
        run: go run ${GITHUB_WORKSPACE}/.github/scripts/publish_release_announcement.go

