name: Publish Release

on:
  workflow_dispatch:
    inputs:
      desc:
        description: 'The markdown of the release'
        required: true
        type: string
      title:
        description: 'The release title'
        required: true
        type: string

jobs:
  upload-zefops:
    name: Deploy zefops docstrings to zef-docs.
    runs-on: ubuntu-20.04
    needs: [check-wheels]
    outputs:
      tag: ${{ steps.tag.outputs.tag }}
    steps:
      - uses: actions/checkout@v2
        with:
          path: /home/runner/work/zef/zef
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Get tag
        id: tag
        run: |
          a=$(python .github/scripts/get_version_from_tag.py)
          b=$?
          [ $b = 0 ] || exit $b
          echo ::set-output name=tag::${a}

      - name: Grab built wheel
        env:
          ZEF_VERSION: ${{ steps.tag.outputs.tag }}
        run: |
          python3 -mpip install zef==${ZEF_VERSION}
        with:
          name: wheels
          path: dist

      - name: Setup python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8

      - name: Install wheel
        run: pip3 install dist/*.whl

      ########
      # Generate docs
      - name: Run extract docstrings script
        run: |
          export PYTHONPATH="${GITHUB_WORKSPACE}/zefDB:$PYTHONPATH"
          echo $PYTHONPATH
          python zefDB/scripts/extract-docstrings.py
      - uses: actions/checkout@v2
        with:
          repository: zefhub/zef-docs
          path: /home/runner/work/zef/zef-docs
          token: ${{ secrets.GIT_ACCESS_KEY }}
          persist-credentials: true
      - run: |
          mv zef-ops.mdx /home/runner/work/zef/zef-docs/docs/zef-ops.mdx
          cd /home/runner/work/zef/zef-docs
          git status
          git config user.email "thedanielforum@gmail.com"
          git config user.name "Zef Bot by Github Actions"
          git add docs/zef-ops.mdx
          git commit -m "Auto generated zef-ops docs from docstrings in Zef repo."
          git push origin master

  make-gh-release:
    name: Release on GitHub
    steps:
      - uses: softprops/action-gh-release@v1
        with:
          body: ${{ github.event.inputs.desc }}
          name: ${{ github.event.inputs.title }}

  publish-announcement:
    name: Publish announcement of new release
    runs-on: ubuntu-20.04
    needs: [upload-zefops]
    steps:
      - uses: actions/checkout@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          persist-credentials: true

      - name: Release announcement
        env:
          MATTERMOST_URL: ${{ secrets.MATTERMOST_URL }}
          CHANNEL: releases
          NAME: ${{ github.event.inputs.title }}
          DESCRIPTION: ${{ github.event.inputs.desc }}
          VERSION_STRING: ${{ needs.upload-zefops.outputs.tag }}
          DOWNLOAD_STRING: "`pip3 install --upgrade zef`"
        run: go run ${GITHUB_WORKSPACE}/.github/scripts/publish_release_announcement.go

