name: Publish Release

on:
  workflow_dispatch:
    inputs:
      tag:
        description: 'The pyzef-x tag of the release'
        required: true
        type: string

jobs:
  upload-zefops:
    name: Deploy zefops docstrings to zef-docs.
    runs-on: ubuntu-20.04
    environment: Release
    steps:
      - uses: actions/checkout@v2
        with:
          path: zef-latest
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Setup python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8

      - name: Grab built wheel
        env:
          ZEF_VERSION: ${{ github.event.inputs.tag }}
        run: |
          python3 -mpip install zef==${ZEF_VERSION}

      ########
      # Generate docs
      - name: Run extract docstrings script
        run: |
          # export PYTHONPATH="${GITHUB_WORKSPACE}/zef:$PYTHONPATH"
          # echo $PYTHONPATH
          python zef-latest/scripts/extract-docstrings.py
      - uses: actions/checkout@v2
        with:
          repository: zefhub/zef-docs
          path: zef-docs
          token: ${{ secrets.GIT_FULL_ACCESS_TOKEN }}
        env:
          VERSION_STRING: ${{ github.event.inputs.tag }}
          TARGET_FILE: docs/reference/zef-ops.mdx
      - run: |
          # Make sure the file hasn't moved
          [ -f zef-docs/${TARGET_FILE} ]
          mv zef-ops.mdx zef-docs/$TARGET_FILE
          cd zef-docs
          git status
          git config user.email "thedanielforum@gmail.com"
          git config user.name "Zef Bot by Github Actions"
          git add ${TARGET_FILE}
          if ! git diff-index --quiet HEAD ; then
            git commit -m "Auto generated zef-ops docs from docstrings in Zef repo for version ${VERSION_STRING}."
            git push origin master
          fi

  publish-announcement:
    name: Publish announcement of new release
    runs-on: ubuntu-20.04
    needs: [upload-zefops]
    steps:
      - uses: actions/checkout@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Get announcement details
        id: release-details
        env:
          ZEF_TAG: ${{ github.event.inputs.tag }}
        run: |
          curl -H "Accept: application/vnd.github.v3+json" https://api.github.com/repos/zefhub/zef/releases/tags/pyzef-${ZEF_TAG} -o curl.out || exit 1
          cat curl.out | jq -re .body > release.body || exit 1
          title=$(cat curl.out | jq -re .name)
          echo ::set-output name=title::${title}

      - name: Release announcement
        env:
          MATTERMOST_URL: ${{ secrets.MATTERMOST_URL }}
          CHANNEL: "releases"
          NAME: ${{ steps.release-details.outputs.title }}
          DESCRIPTION_FILE: "release.body"
          VERSION_STRING: ${{ github.events.inputs.tag }}
          DOWNLOAD_STRING: "`pip3 install --upgrade zef`"
        run: go run .github/scripts/publish_release_announcement.go

