name: Publish Release

on:
  release:
    types: [published, create]

jobs:
  check-license:
    uses: ./.github/workflows/check-license.yml

  upload-zefops:
    name: Deploy zefops docstrings to zef-docs.
    runs-on: ubuntu-20.04
    needs: [check-wheels]
    outputs:
      tag: ${{ steps.tag.outputs.tag }}
    strategy:
      matrix:
        python-version: [3.8]
    steps:
      steps:
        - name: Get tag
          id: tag
          # This will probably need to massaging to find the latest tag amongst all tags
          run: |
            echo ::set-output name=tag::${GITHUB_REF##*/pyzef-}

      # - uses: actions/checkout@v2
      #   with:
      #     path: /home/runner/work/zefDB/zefDB/zefDB
      #     token: ${{ secrets.GITHUB_TOKEN }}

      - name: Grab built wheel
        env:
          ZEF_VERSION: ${{ steps.tag.outputs.tag }}
        run: |
          python3 -mpip install zef==${ZEF_VERSION}
        with:
          name: wheels
          path: dist

      - name: Setup python
        uses: actions/setup-python@v2
        with:
          python-version: ${{ inputs.python-version }}

      - name: Install wheel
        run: pip3 install dist/*.whl

      ########
      # Generate docs
      - name: Run extract docstrings script
        run: |
          export PYTHONPATH="${GITHUB_WORKSPACE}/zefDB:$PYTHONPATH"
          echo $PYTHONPATH
          python zefDB/scripts/extract-docstrings.py
      - uses: actions/checkout@v2
        with:
          repository: synchronoustechnologies/zef-docs
          path: /home/runner/work/zefDB/zefDB/zef-docs
          token: ${{ secrets.GIT_ACCESS_KEY }}
          persist-credentials: true
      - run: |
          mv zef-ops.mdx /home/runner/work/zefDB/zefDB/zef-docs/docs/zef-ops.mdx
          cd /home/runner/work/zefDB/zefDB/zef-docs
          git status
          git config user.email "thedanielforum@gmail.com"
          git config user.name "Zef Bot by Github Actions"
          git add docs/zef-ops.mdx
          git commit -m "Auto generated zef-ops docs from docstrings in Zef repo."
          git push origin master

  publish-announcement:
    name: Publish announcement of new release
    runs-on: ubuntu-20.04
    needs: [upload-zefops]
    if: ${{ github.event.release.prerelease == false) }}
    steps:
      - uses: actions/checkout@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          persist-credentials: true

      - name: Release announcement
        env:
          MATTERMOST_URL: ${{ secrets.MATTERMOST_URL }}
          CHANNEL: releases
          NAME: ${{ github.event.release.name }}
          DESCRIPTION: ${{ github.event.release.body }}
          VERSION_STRING: ${{ needs.upload-zefops.outputs.tag }}
          DOWNLOAD_STRING: "`pip3 install --upgrade zef`"
        run: go run ${GITHUB_WORKSPACE}/.github/scripts/publish_release_announcement.go

