name: Testing Windows local compile

on:
 push:
   branches:
     - windows-build

jobs:
  build-wheels:
    name: Build wheels
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-20.04, windows-latest]
        python-version: ["3.10"]
    env:
      ZEFHUB_AUTH_KEY: "GUEST"

    steps:
      ########
      # Git things
      - uses: actions/checkout@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Build
        uses: ./.github/actions/build
        timeout-minutes: 15
        with:
          python-version: ${{ matrix.python-version }}
          os: ${{ matrix.os }}

