name: Testing Windows build

on:
 push:
   branches:
     - windows-build

jobs:
  check-license:
    uses: ./.github/workflows/check-license.yml
  build-wheels:
    needs: check-license
    name: Build wheels
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-20.04, windows-latest]
        python-version: ["cp310"]
    env:
      ZEFHUB_AUTH_KEY: "GUEST"

    steps:
      ########
      # Git things
      - uses: actions/checkout@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Build wheels
        uses: pypa/cibuildwheel@v2.4.0
        with:
          package-dir: python
        env:
          CIBW_BUILD: "${{ matrix.python-version}}*"

